<a href="https://colab.research.google.com/github/DavidZD5/Mineria-de-datos/blob/main/MineriaDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos


## Primer Parcial


### Introduccion

#### Conceptos
La minería de datos (o data mining) es el proceso de analizar grandes volúmenes de datos para descubrir patrones, tendencias y correlaciones ocultas que no son evidentes a simple vista, transformando así datos brutos en conocimiento útil para la toma de decisiones estratégicas, predicción de resultados, optimización de procesos y aumento de ingresos. Utiliza técnicas estadísticas y de aprendizaje automático para encontrar anomalías y relaciones que permitan predecir comportamientos futuros, como la fuga de clientes o la compra conjunta de productos.


#### Ciencia de Datos
 Es un campo multidisciplinario que combina estadística, matemáticas, inteligencia artificial y computación para analizar grandes volúmenes de datos (Big Data) y extraer conocimiento significativo, patrones y tendencias, con el fin de apoyar la toma de decisiones, hacer predicciones y resolver problemas en diversas industrias. Implica todo el ciclo de vida de los datos, desde su recolección y limpieza hasta su análisis mediante técnicas como el Aprendizaje Automático (Machine Learning) y la visualización para generar información útil y estratégica.

#### Acceder a la documentación con ?

El lenguaje Python y su ecosistema de ciencia de datos se construyen pensando en el usuario, y una parte importante de ello es el acceso a la documentación.
Cada objeto de Python contiene una referencia a una cadena, conocida como *docstring*, que en la mayoría de los casos contendrá un resumen conciso del objeto y cómo usarlo.
Python tiene una función `help` integrada que puede acceder a esta información e imprimir los resultados.
Por ejemplo, para ver la documentación de la función `len` integrada, puede hacer lo siguiente:



In [ ]:
In [1]: help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Debido a que encontrar ayuda sobre un objeto es tan común y útil, IPython y Jupyter introducen el carácter `?` como una abreviatura para acceder a esta documentación y otra información relevante:


In [ ]:
In [2]: len?

Esta notación funciona para casi cualquier cosa, incluidos los métodos de objeto:

In [ ]:
In [3]: L = [1, 2, 3]
In [4]: L.insert?

o incluso los propios objetos, con la documentación de su tipo:

In [ ]:
In [5]: L?

Es importante destacar que esto también funcionará con funciones u otros objetos que crees tú mismo.
Aquí definiremos una pequeña función con una cadena de documentación:

In [ ]:
In [6]: def square(a):
  ....:     """Return the square of a."""
  ....:     return a ** 2
  ....:

Ahora usaremos el signo de interrogación `?` para encontrar esta cadena de documentación:

1. Elemento de lista
2. Elemento de lista

In [ ]:
In [7]: square?

#### Accediendo al código fuente con ??

Dado que el lenguaje Python es tan legible, generalmente se puede obtener un mayor nivel de comprensión leyendo el código fuente del objeto que te interesa.
IPython y Jupyter ofrecen un acceso directo al código fuente con el doble signo de interrogación (`??`):

In [ ]:
In [8]: square??

Si experimentas con esto, notarás que a veces el sufijo `??` no muestra el código fuente: esto generalmente se debe a que el objeto en cuestión no está implementado en Python, sino en C o algún otro lenguaje de extensión compilado.
En este caso, el sufijo `??` genera el mismo resultado que el sufijo `?`.
Esto ocurre especialmente con muchos de los objetos y tipos integrados de Python, incluyendo la función `len` mencionada anteriormente:

In [ ]:
In [9]: len??

####Exploración de módulos con la tecla Tabulador

Otra interfaz útil es el uso de la tecla Tabulador para autocompletar y explorar el contenido de objetos, módulos y espacios de nombres.
En los siguientes ejemplos, usaré `<TAB>` para indicar cuándo se debe presionar la tecla Tabulador.

Completado de tabulaciones del contenido de objetos

Cada objeto de Python tiene varios atributos y métodos asociados.
Al igual que la función `help` mencionada anteriormente, Python incorpora una función `dir` que devuelve una lista de estos atributos, pero la interfaz de completado de tabulaciones es mucho más fácil de usar en la práctica.
Para ver una lista de todos los atributos disponibles de un objeto, puede escribir el nombre del objeto seguido de un punto ("`.`") y la tecla Tab.

In [ ]:
In [10]: dir(L)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

Para limitar la lista, puede escribir el primer carácter o varios caracteres del nombre y la tecla Tab encontrará los atributos y métodos coincidentes:

In [ ]:
# ver atributos que empiezan con 'c'
In [10]: print([attr for attr in dir(L) if attr.startswith('c')])

# ver atributos que empiezan con 'co'
In [10]: print([attr for attr in dir(L) if attr.startswith('co')])

['clear', 'copy', 'count']
['copy', 'count']


Si solo hay una opción, al presionar la tecla Tab se completará la línea automáticamente.
Por ejemplo, lo siguiente se reemplazará instantáneamente por `L.count`:

In [ ]:
In [10]: L.count

<function list.count(value, /)>

Aunque Python no establece una distinción estricta entre atributos públicos/externos y privados/internos, por convención se utiliza un guion bajo para indicar estos últimos.
Para mayor claridad, estos métodos privados y especiales se omiten de la lista por defecto, pero es posible listarlos escribiendo explícitamente el guion bajo:

In [ ]:
In [10]: print([attr for attr in dir(L) if attr.startswith('_')])

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__']


Completar tabulaciones al importar

El completado de tabulación también es útil al importar objetos desde paquetes.
Aquí lo usaremos para encontrar todas las posibles importaciones en el paquete `itertools` que comiencen por `co`:

In [ ]:
In [10]: import itertools
print([attr for attr in dir(itertools) if attr.startswith('co')])

['combinations', 'combinations_with_replacement', 'compress', 'count']


De manera similar, puede usar la función de completar tabulaciones para ver qué importaciones están disponibles en su sistema (esto cambiará dependiendo de qué scripts y módulos de terceros sean visibles para su sesión de Python):

Más allá del autocompletado con tabulación: Coincidencia con comodines

El autocompletado con tabulación es útil si conoce los primeros caracteres del nombre del objeto o atributo que busca, pero no es de mucha ayuda si desea encontrar coincidencias en el medio o al final del nombre.
Para este caso, IPython y Jupyter ofrecen un método de coincidencia con comodines para nombres que usan el carácter `*`.

Por ejemplo, podemos usar esto para listar todos los objetos del espacio de nombres cuyo nombre termine en `Warning`:

In [ ]:
In [10]: *Warning?

Observe que el carácter `*` coincide con cualquier cadena, incluso la cadena vacía.

De forma similar, supongamos que buscamos un método de cadena que contiene la palabra `find` en su nombre.
Podemos buscarlo de esta manera:

In [ ]:
In [11]: str.*find*?

### IPython Magic Commands

#### Timing Code Execution: %timeit

In [17]:
#El comando magico %timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

68.6 µs ± 921 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
#Comando magico %%timeit sirve para evaluar el desempeño solo que este
#abarca varias lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

93.4 µs ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### IPython and Shell Commands

In [18]:
!ls

sample_data


In [19]:
%cd sample_data

/content/sample_data


In [20]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [21]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [22]:
#sirve para ver las variables de entorno
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '593a16418735',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

### Understanding Data Types in Python


In [25]:
import numpy as np

In [26]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [27]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [28]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [29]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [30]:
# nested lists result in multi-dimensional arrays (ciclos anidados)
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])